changelog:
  exclude:
    labels:
      - skip-changelog
      - dependencies
    authors:
      - dependabot
      - github-actions
  categories:
    - title: 🚀 Features
      labels: [feature, enhancement]
    - title: 🐛 Bug Fixes
      labels: [bug, fix]
    - title: 🧰 Maintenance
      labels: [chore, refactor, ci, docs]
    - title: 🔒 Security
      labels: [security]
    - title: ⚠️ Breaking Changes
      labels: [breaking-change]
    - title: Other Changes
      labels: ["*"]   # catch-all for unlabeled PRs
