# Build stage
FROM golang:1.21.5 AS builder
WORKDIR /app
COPY . .
RUN chmod +x autobuild.sh
RUN ./autobuild.sh

# Run stage
FROM alpine:20231219
WORKDIR /app
COPY --from=builder ./bin/api /app/
COPY --from=builder ./bin/addSite /app/
COPY --from=builder ./bin/removeSite /app/
COPY --from=builder ./config.yaml /app/

# Expose port 8080 to the outside world
EXPOSE 8080

# Command to run the executable
CMD ["./api"]
