--- Dockerfile.orig
+++ Dockerfile
@@ -13,6 +13,7 @@
 RUN echo "deb ${CHROMIUM_DEB_SITE}/ sid main" >> /etc/apt/sources.list \
   && wget -qO- https://ftp-master.debian.org/keys/archive-key-12.asc | gpg --dearmor > /etc/apt/trusted.gpg.d/debian-archive-keyring.gpg \
   && wget -qO- https://ftp-master.debian.org/keys/archive-key-12-security.asc | gpg --dearmor > /etc/apt/trusted.gpg.d/debian-archive-security-keyring.gpg \
+  && for d in bin lib lib32 lib64 libo32 libx32 sbin; do dpkg-divert --package base-files --no-rename --remove /$d; done \
   && apt-get update -qqy \
   && if [ "${CHROMIUM_VERSION}" = "latest" ]; \
       then apt-get -qqy --no-install-recommends install chromium-common chromium chromium-l10n chromium-driver; \
