--- ./docker-selenium/NodeChromium/Dockerfile	2024-09-07 00:06:57
+++ ./docker-selenium/NodeChromium/Dockerfile_Chromium_ARM64_4.21.0	2024-09-07 00:07:30
@@ -7,12 +7,37 @@
 USER root

 # Install Chromium
-RUN echo "deb http://deb.debian.org/debian/ sid main" >> /etc/apt/sources.list \
-  && apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 0E98404D386FA1D9 6ED0E7B82643E131 \
-  && apt-get update -qqy \
-  && apt-get -qqy install chromium \
-  && rm -rf /var/lib/apt/lists/* /var/cache/apt/*
+#RUN echo "deb http://deb.debian.org/debian/ sid main" >> /etc/apt/sources.list \
+#  && apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 0E98404D386FA1D9 6ED0E7B82643E131 \
+#  && apt-get update -qqy \
+#  && apt-get -qqy install chromium \
+# && rm -rf /var/lib/apt/lists/* /var/cache/apt/*

+# Add the Debian buster repositories
+RUN echo "deb [arch=arm64 signed-by=/usr/share/keyrings/debian-buster.gpg] http://deb.debian.org/debian buster main" > /etc/apt/sources.list.d/debian-buster.list \
+    && echo "deb [arch=arm64 signed-by=/usr/share/keyrings/debian-buster-updates.gpg] http://deb.debian.org/debian buster-updates main" >> /etc/apt/sources.list.d/debian-buster.list \
+    && echo "deb [arch=arm64 signed-by=/usr/share/keyrings/debian-security-buster.gpg] http://deb.debian.org/debian-security buster/updates main" >> /etc/apt/sources.list.d/debian-buster.list
+
+# Add the Debian GPG keys
+RUN apt-key adv --keyserver keyserver.ubuntu.com --recv-keys DCC9EFBF77E11517 648ACFD622F3D138 112695A0E562B32A \
+    && apt-key export DCC9EFBF77E11517 | gpg --dearmour -o /usr/share/keyrings/debian-buster.gpg \
+    && apt-key export 648ACFD622F3D138 | gpg --dearmour -o /usr/share/keyrings/debian-buster-updates.gpg \
+    && apt-key export 112695A0E562B32A | gpg --dearmour -o /usr/share/keyrings/debian-security-buster.gpg
+
+# Configure apt pinning for Chromium
+RUN echo "Package: *" > /etc/apt/preferences.d/chromium.pref \
+    && echo "Pin: release a=jammy" >> /etc/apt/preferences.d/chromium.pref \
+    && echo "Pin-Priority: 500" >> /etc/apt/preferences.d/chromium.pref \
+    && echo "" >> /etc/apt/preferences.d/chromium.pref \
+    && echo "Package: chromium*" >> /etc/apt/preferences.d/chromium.pref \
+    && echo "Pin: origin deb.debian.org" >> /etc/apt/preferences.d/chromium.pref \
+    && echo "Pin-Priority: 700" >> /etc/apt/preferences.d/chromium.pref
+
+# Install Chromium from Debian buster
+RUN apt-get update \
+    && apt-get install -y chromium \
+    && rm -rf /var/lib/apt/lists/* /var/cache/apt/*
+
 #=================================
 # Chromium Launch Script Wrapper
 #=================================
@@ -32,6 +57,9 @@
 COPY chrome-cleanup.sh /opt/bin/chrome-cleanup.sh
 COPY chrome-cleanup.conf /etc/supervisor/conf.d/chrome-cleanup.conf

+# Disable Debian repositories after installing Chromium
+RUN rm /etc/apt/sources.list.d/debian-buster.list
+
 USER ${SEL_UID}

 #============================================
