name: Build and Push Multi‑Arch Docker Images

on:
  workflow_dispatch:  # Only run manually

env:
  REGISTRY: docker.io
  IMAGE_OWNER: zfpsystems
  IMAGE_TAG: latest  # change to version tag or commit SHA if needed

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up QEMU for cross-platform building
        uses: docker/setup-qemu-action@v3

      - name: Build & Push crowler-api
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            -f Dockerfile.searchapi \
            -t $REGISTRY/$IMAGE_OWNER/crowler-api:$IMAGE_TAG \
            --push .

      - name: Build & Push crowler-events
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            -f Dockerfile.events \
            -t $REGISTRY/$IMAGE_OWNER/crowler-events:$IMAGE_TAG \
            --push .

      - name: Build & Push crowler-engine
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            -f Dockerfile.thecrowler \
            -t $REGISTRY/$IMAGE_OWNER/crowler-engine:$IMAGE_TAG \
            --push .

      - name: Build & Push crowler-db
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            --build-arg TIMEZONE=UTC \
            -f Dockerfile.db \
            -t $REGISTRY/$IMAGE_OWNER/crowler-db:$IMAGE_TAG \
            --push .
