name: Go-VulnCheck

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  osv-scanner:
    runs-on: ubuntu-latest

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@b09bb98e06d4d774595224525879c09bc6e98c40 # v2.20.1
        with:
          egress-policy: audit

      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Set up Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version-file: go.mod

      - name: Clean Go environment and install dependencies
        run: |
          go clean -cache -modcache -i -r
          go mod download
          go mod tidy

      - name: Build the project
        run: |
          go build ./...
          go test ./...

      - name: Install govulncheck
        run: go install golang.org/x/vuln/cmd/govulncheck@latest

      - name: Download OSV-Scanner
        run: |
          wget https://github.com/google/osv-scanner/releases/download/v1.8.1/osv-scanner_linux_amd64 -O osv-scanner
          chmod +x osv-scanner

      #- name: Run OSV-Scanner
      #  run: ./osv-scanner --recursive .

      - name: Run govulncheck
        run: govulncheck ./...
